[package]
name = "rust_bridge_scorecard_api_backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.20"
bcrypt = "0.15.0"
mongodb = "2.7.1"
serde_json = "1.0.108"
tokio = "1.34.0"
