#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $MY_USER WITH SUPERUSER PASSWORD '$MY_PASSWORD';
    CREATE DATABASE $MY_USER;
    GRANT ALL PRIVILEGES ON DATABASE $MY_USER TO $MY_USER;
EOSQL