application:
  port: 4040
  hmac_secret: "for_testing_only_sdfsdf_sdwetergrtbfb_ert343454tergdfggergergergergwsdfwefqwedqwedsdvergerg3e4wt34werwefwe"
  jwt_secret: "for_testing_only_sdfsdf_sdwetergrtbfb_ert343454tergdfggergergergergwsdfwefqwedqwedsdvergerg3e4wt34werwefwe"
database:
  host: "localhost"
  port: 5432
  database_name: "bridge_scorecard_development"
  tls: false
  min_pool_size: 5
  max_pool_size: 10
  username: 
  password: 
redis_uri: "redis://127.0.0.1:6379"